-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        #require_serial: true
        files: \.py$

    -   id: black
        name: black
        entry: black --check
        language: system
        types: [python]
        #additional_dependencies: ['black']